Build openbsd-compat/clock_gettime.c with libasr
MacOS does not implement `clock_gettime()`. The implementation in openbsd-compat is
needed to use any `clock_gettime()` calls in libasr. Building libasr and
linking libasr with other binaries do not cause any errors, but, try to run the
linked binary and this is what appears...

    dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
      Referenced from: /usr/local/opt/libasr/lib/libasr.0.dylib
      Expected in: flat namespace

    dyld: Symbol not found: _clock_gettime
      Referenced from: /usr/local/opt/libasr/lib/libasr.0.dylib
      Expected in: flat namespace